Revamp README
mamba-org/mamba pull request #1842
Opened 2022-08-05 21:52 UTC by jonashaag

cc @pavelzw 

WDYT about deduplicating README further and listing some nice features there. What are some nice Mamba/Micromamba features other than `repoquery` and lock file support @wolfv?

2022-08-06 08:02 UTC, pavelzw reviewed
We should unify capitalization... Either conda, mamba and micromamba, `conda`, `mamba` and `micromamba` or Conda, Mamba and Micromamba. 
As from what I've seen, it's mainly `conda`, `mamba` and `micromamba` in the documentation (with some exceptions).

The first sentence

> Mamba is a reimplementation of the conda package manager in C++.

would probably also need to be adjusted to `mamba`. GitHub didn't let me suggest changes on this one though...

2022-08-08 15:24 UTC, jonashaag commented
@wolfv do you like the changes?

2022-08-08 15:30 UTC, pavelzw requested changes

2022-08-08 15:30 UTC, pavelzw commented on README.md
> +`micromamba` can be used to install lock files generated by (conda-lock)[https://conda-incubator.github.io/conda-lock/] without having to install `conda-lock`.
```suggestion
`micromamba` can be used to install lock files generated by [conda-lock](https://conda-incubator.github.io/conda-lock/) without having to install `conda-lock`.
```

2022-08-08 17:34 UTC, merged

2022-08-08 17:35 UTC, wolfv commented
Thanks, nice improvement!

@jonashaag if it's OK for you, please don't add branches in this repo (still use your personal fork) :)

Cheers!

2022-08-08 19:40 UTC, jonashaag commented
Whoops, seems to be GitHub’s default behavior. Will try to avoid it in the future.