First version/steps of unraveling `fetch` code and wrapping libcurl
mamba-org/mamba pull request #2376
Opened 2023-03-14 17:38 UTC by Hind-M

Part of #2356 fix
Based on #2366

2023-03-15 08:26 UTC, JohanMabille commented
This one can be rebased now that #2366 has been merged

2023-03-23 15:00 UTC, JohanMabille requested changes

2023-03-23 16:57 UTC, Hind-M commented on libmamba/src/core/curl.cpp
> +    CURL* CURLHandle::handle()
I added a comment but yes that's the plan.

2023-03-23 16:58 UTC, Hind-M commented on libmamba/src/core/curl.hpp
>  #include <curl/curl.h>
Added a comment.

2023-03-23 21:21 UTC, merged