chore: some CMake cleanup
mamba-org/mamba pull request #3564
Opened 2024-10-23 16:43 UTC by henryiii

Some things I noticed when trying something locally.

2024-10-23 16:46 UTC, henryiii commented on CMakeLists.txt
> -cmake_policy(SET CMP0077 NEW) # Introduced in cmake 3.13
Setting the minimum version of CMake sets all policies to NEW that were introduced on or before that value. (Also true if you set a version range, like 3.16...3.30)

2024-10-23 16:46 UTC, henryiii commented on docs/source/developer_zone/dev_environment.rst
> +    micromamba activate mamba
There's no `-n` here.

2024-10-23 16:46 UTC, henryiii commented on libmamba/CMakeLists.txt
> +find_package(fmt CONFIG REQUIRED)
Using `CONFIG` explicitly makes the error message better. I didn't go through every one to figure out whether they were CONFIG or MODULE, but these are some of the first ones hit, so error message is important for these.

2024-10-23 16:46 UTC, henryiii commented on libmambapy/CMakeLists.txt
> +find_package(Python COMPONENTS Interpreter Development.Module)
The default `Development` looks for the `Embed` target too, which isn't required and sometimes (like on manylinux) not available.

2024-10-24 07:34 UTC, jjerphan approved these changes
Hi @henryiii,

Thank you for bringing your expertise in build system and meta-build systems with this contribution!

Edit: I don't know whether the failures on Windows are related to that, and I can't debug it.

2024-10-24 18:08 UTC, henryiii commented
The PR after this one has the same windows error, and the one before this one claims to fix something on Windows.

2024-10-24 18:28 UTC, jjerphan commented
#3555 fixes an issue related to tests under Windows.

The error here is due to vcpkg which is used for the static builds of micromamba on Windows — this might be beyond our control.

2024-10-25 08:59 UTC, JohanMabille approved these changes

2024-10-25 09:04 UTC, JohanMabille commented
This looks like a network issue, libxml2 is available at [https://gitlab.gnome.org//GNOME/libxml2/-/archive/v2.11.9/libxml2-v2.11.9.tar.gz](https://gitlab.gnome.org//GNOME/libxml2/-/archive/v2.11.9/libxml2-v2.11.9.tar.gz:)

2024-10-25 09:24 UTC, JohanMabille commented on libmamba/CMakeLists.txt
> +            find_package(LibArchive CONFIG REQUIRED)
I t looks like LibArhcive does not provide a cmake config file on Windows.

2024-10-25 09:27 UTC, JohanMabille requested changes
It looks like the  LibArchive vcpkg package does not provide a cmake config file

2024-10-25 09:27 UTC, JohanMabille commented on libmamba/CMakeLists.txt
> +            find_package(LibArchive CONFIG REQUIRED)
```suggestion
            find_package(LibArchive REQUIRED)
```

2024-10-25 13:48 UTC, henryiii commented on libmamba/CMakeLists.txt
> +            find_package(LibArchive CONFIG REQUIRED)
Ah, my mistake: https://cmake.org/cmake/help/latest/module/FindLibArchive.html

```suggestion
            find_package(LibArchive MODULE REQUIRED)
```

2024-10-28 10:58 UTC, JohanMabille approved these changes

2024-10-28 10:58 UTC, JohanMabille commented
Thanks!

2024-10-28 10:58 UTC, merged