Fix install using explicit url
mamba-org/mamba pull request #3710
Opened 2024-12-24 14:52 UTC by Hind-M

Fix #3304

2024-12-27 10:57 UTC, Hind-M commented
> Commit [ac3c921](https://github.com/mamba-org/mamba/commit/ac3c9210b21c9fc919f11f08efa1aef61225d1de) looks very suspicious to me. Assuming `util::contains` is roughly `strstr`, won't this match lots of package URLs simply because the path/channel/target/name/version/build happens to contain `ghcr`?

Yes, but that should be unlikely. I changed the condition though to something more robust.

2025-01-02 15:36 UTC, jjerphan commented on libmamba/src/core/package_fetcher.cpp
> +                )))
Can we come up with a private method for this condition testing OCI (from what I can understand) as well as some background in this PR?

2025-01-03 08:36 UTC, JohanMabille requested changes

2025-01-03 08:36 UTC, JohanMabille commented on libmamba/src/core/package_fetcher.cpp
> +                    "https://pkg-containers.githubusercontent.com/"
- We should not use a hard-coded URL here, but a constant initialized to that value.
- Capturing the diferent conditions in small functions would make the code easier to read.

2025-01-03 12:39 UTC, jjerphan approved these changes
Thank you, @Hind-M.

2025-01-03 12:39 UTC, jjerphan commented on libmamba/src/core/package_fetcher.cpp
> +    bool PackageFetcher::use_explicit_url() const
Nitpick.
```suggestion
    bool PackageFetcher::use_explicit_https_url() const
```

2025-01-03 12:39 UTC, jjerphan commented on libmamba/src/core/package_fetcher.cpp
>      }
How about?

```c++
    std::string PackageFetcher::channel() const
    {
        if (is_local_package() || use_explicit_url())
        {
            // Use explicit url or local package path
            // to fetch package, leaving the channel empty.
            return "";
        }
        return m_package_info.channel;
    }
```

2025-01-03 12:39 UTC, jjerphan commented on libmamba/src/core/package_fetcher.cpp
>          }
How about?

```c++
    std::string PackageFetcher::url_path() const
    {
        if (is_local_package() || use_explicit_url())
        {
            // Use explicit url or local package path
            // to fetch package.
            return m_package_info.package_url;
        }
        return util::concat(m_package_info.platform, '/', m_package_info.filename);
    }
```

2025-01-06 11:35 UTC, merged